// eslint-disable-next-line no-unused-vars
var songlist =
  [
    {
      'listname': 'exemple',
      'done': false,
      'theme': 'Exemple',
      'type': 'single',
      'bonus': 'Alain Chamfort',
      'title': 'Exemple',
      'subtitle': 'On fait un test pour du beurre (avec des anagrammes) !',
      'songs': [
        { 'name': 'Charlélie Couture', 'alternate': '', 'fullname': 'Charlélie Couture - Comme un Avion sans aile', 'youtube': 'https://www.youtube.com/watch?v=wTrEQbwoWw4', 'singletext': 'Qui est Couturier Alleché ?' },
        { 'name': 'Les Chaussettes Noires', 'alternate': 'Chaussettes Noires', 'fullname': 'Les Chaussettes Noires - Daniela', 'youtube': 'https://www.youtube.com/watch?v=5Qe6GRl6E7k', 'singletext': 'Qui sont Les Secouristes Hantés ?' },
        { 'name': 'IAM', 'alternate': '', 'fullname': 'IAM - Je danse le MIA', 'youtube': 'https://www.youtube.com/watch?v=4a1-1qlhb5g', 'singletext': 'Qui sont MAI ?' },
      ]
    },
    {
      'listname': 'journee',
      'type': 'single',
      'bonus': 'Petit Biscuit',
      'done': false,
      'title': 'Journée Mondiale - Sans Régime',
      'subtitle': 'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
      'songs': [
        { 'name': 'Lio', 'alternate': '', 'fullname': 'Lio - Banana Split', 'youtube': 'https://www.youtube.com/watch?v=C8uGeVygQ0Q' },
        { 'name': 'Aerosmith', 'alternate': '', 'fullname': 'Aerosmith - Eat the Rich', 'youtube': 'https://www.youtube.com/watch?v=VSrloB4OS1Q' },
        { 'name': 'Cocoon', 'alternate': '', 'fullname': 'Cocoon - Sushi', 'youtube': 'https://www.youtube.com/watch?v=rsDOANAc-Dg' },
        { 'name': 'Suzane', 'alternate': '', 'fullname': 'Suzane - Pas beaux', 'youtube': 'https://www.youtube.com/watch?v=n75ZXmmTv4A' },
        { 'name': 'Henri Dès', 'alternate': '', 'fullname': 'Henri Dès - Gateau', 'youtube': 'https://www.youtube.com/watch?v=sU4M8rdOpOM' },
        { 'name': 'Joe Dassin', 'alternate': '', 'fullname': 'Joe Dassin - Le Petit Pain au Chocolat', 'youtube': 'https://www.youtube.com/watch?v=A_8g3df4zcI' },
        { 'name': 'Hot Butter', 'alternate': '', 'fullname': 'Hot Butter - Pop Corn', 'youtube': 'https://www.youtube.com/watch?v=ykPjHCypx4A' },
        { 'name': 'Billy Ze Kick', 'alternate': '', 'fullname': 'Billy Ze Kick - Mangez-moi', 'youtube': 'https://www.youtube.com/watch?v=taOsuVhXqzY' },
        { 'name': 'Hubert-Félix Thiéfaine', 'alternate': '', 'fullname': 'Hubert-Félix Thiéfaine - La Cancoillotte', 'youtube': 'https://www.youtube.com/watch?v=X1Xcoc97GvE' },
        { 'name': 'Camille', 'alternate': '', 'fullname': 'Camille - Le Festin', 'youtube': 'https://www.youtube.com/watch?v=-QuVe-hjMs0' },
        { 'name': 'Louis Armstrong', 'alternate': '', 'fullname': 'Louis Armstrong - Cheesecake', 'youtube': 'https://www.youtube.com/watch?v=QQYqGsoYMzg' },
        { 'name': 'Sanseverino', 'alternate': '', 'fullname': 'Sanseverino - Maigrir', 'youtube': 'https://www.youtube.com/watch?v=VizjETIFsjs' },
      ]
    },
    {
      'listname': 'franglais',
      'type': 'single',
      'bonus': 'Richard Gotainer',
      'done': false,
      'title': 'Les Franglaises',
      'subtitle': 'Retrouvez les interprètes frnaçais des chansons reprises en anglais ! (Prénom + Nom / Groupe)',
      'songs': [
        { 'name': 'Michel Polnareff', 'alternate': '', 'fullname': 'Michel Polnareff - Âme Caline (Peggy March)', 'youtube': 'https://www.youtube.com/watch?v=M0YclIN8tjk' },
        { 'name': 'Dalida', 'alternate': '', 'fullname': 'Dalida - Mourir sur Scène (Shirley Bassey)', 'youtube': 'https://www.youtube.com/watch?v=6iGHmbnByHY' },
        { 'name': 'Alain Bashung', 'alternate': '', 'fullname': 'Alain Bashung - Vertige de l\'Amour (Johnny Hallyday)', 'youtube': 'https://www.youtube.com/watch?v=oY500cFm37A' },
        { 'name': 'Nino Ferrer', 'alternate': '', 'fullname': 'Nino Ferrer - Mirza (Casey Jones and the Governors)', 'youtube': 'https://www.youtube.com/watch?v=hOz52bd_RTs' },
        { 'name': 'De Palmas', 'alternate': 'Gérald de Palmas', 'fullname': 'De Palmas - Tomber (Céline Dion)', 'youtube': 'https://www.youtube.com/watch?v=4JDEizllXbk' },
        { 'name': 'Michel Fugain', 'alternate': '', 'fullname': 'Michel Fugain - Je n\'aurai pas le temps (John Rowles)', 'youtube': 'https://www.youtube.com/watch?v=-M9ztgd6UoU' },
        { 'name': 'Georges Brassens', 'alternate': '', 'fullname': 'Georges Brassens - Chanson pour l\'Auvergnat (Pierre de Gaillande)', 'youtube': 'https://www.youtube.com/watch?v=E-dJs1Lnvzs' },
        { 'name': 'Michel Delpech', 'alternate': '', 'fullname': 'Michel Delpech - Wight is Wight (Sandie Shaw)', 'youtube': 'https://www.youtube.com/watch?v=twq1ZuJ-QQ8' },
        { 'name': 'Stromae', 'alternate': '', 'fullname': 'Stromae - Alors on Danse (Kellylee Evans)', 'youtube': 'https://www.youtube.com/watch?v=pNXdY5M5Bi0' },
        { 'name': 'Serge Gainsbourg', 'alternate': '', 'fullname': 'Serge Gainsbourg - Ballade de Melody Nelson (Placebo)', 'youtube': 'https://www.youtube.com/watch?v=_MEwIPYdSJs&t=12s' },
        { 'name': 'Marc Lavoine', 'alternate': '', 'fullname': 'Marc Lavoine - Elle a les yeux revolvers (The Flying Pickets)', 'youtube': 'https://www.youtube.com/watch?v=JbAdHss7od4' },
        { 'name': 'Axel Bauer', 'alternate': '', 'fullname': 'Axel Bauer - Cargo (Roger Daltrey)', 'youtube': 'https://www.youtube.com/watch?v=FtWCceuwYMo' },
      ]
    },
    {
      'listname': 'gus',
      'type': 'gus',
      'bonus': 'Chinese Man',
      'done': false,
      'title': 'Recyclage du thème de Gus #2',
      'subtitle': 'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) et le nombre d\'albums studios sortis !',
      'songs': [
        { 'name': 'Led Zeppelin', 'alternate': '', 'fullname': 'Led Zeppelin - The Battle of Evermore', 'minutes': '9', 'youtube': 'https://www.youtube.com/watch?v=88b0OYxdtyM' },
        { 'name': 'Chicago', 'alternate': '', 'fullname': 'Chicago - If You Leave Me Now', 'minutes': '24', 'youtube': 'https://www.youtube.com/watch?v=-9_d-sFhmRM' },
        { 'name': 'Lauryn Hill', 'alternate': '', 'fullname': 'Lauryn Hill - Doo Wop', 'minutes': '1', 'youtube': 'https://www.youtube.com/watch?v=T6QKqFPRZSA' },
        { 'name': 'Heart', 'alternate': '', 'fullname': 'Heart - Barracuda', 'minutes': '16', 'youtube': 'https://www.youtube.com/watch?v=VdOkQ6THDVw' },
        { 'name': 'David Bowie', 'alternate': '', 'fullname': 'David Bowie - The Man Who Sold the World', 'minutes': '26', 'youtube': 'https://www.youtube.com/watch?v=u3MX-rUtS6M' },
        { 'name': 'Elton John', 'alternate': '', 'fullname': 'Elton John - Daniel', 'minutes': '33', 'youtube': 'https://www.youtube.com/watch?v=7mHJ0TeHak8' },
        { 'name': 'Renaud', 'alternate': '', 'fullname': 'Renaud - Je Suis une Bande de Jeune', 'minutes': '18', 'youtube': 'https://www.youtube.com/watch?v=yKQP0_sgjwc' },
        { 'name': 'Jeff Buckley', 'alternate': '', 'fullname': 'Jeff Buckley - Lilac Wine', 'minutes': '1', 'youtube': 'https://www.youtube.com/watch?v=7wj0zxFcHQA' },
        { 'name': 'Toto', 'alternate': '', 'fullname': 'Toto - Hold the Line', 'minutes': '14', 'youtube': 'https://www.youtube.com/watch?v=htgr3pvBr-I' },
        { 'name': 'Black Sabbath', 'alternate': '', 'fullname': 'Black Sabbath - Children of the Grave', 'minutes': '19', 'youtube': 'https://www.youtube.com/watch?v=5Izb7fy5bAk' },
        { 'name': 'Bob Dylan', 'alternate': '', 'fullname': 'Bob Dylan - Girl From the North Country', 'minutes': '39', 'youtube': 'https://www.youtube.com/watch?v=rK1Rn_eoeeE' },
        { 'name': 'Stevie Nicks', 'alternate': '', 'fullname': 'Stevie Nicks - Edge of Seventeen', 'minutes': '8', 'youtube': 'https://www.youtube.com/watch?v=3oZunnY-Cbs' },]
    },
    {
      'listname': 'year',
      'done': false,
      'type': 'year',
      'bonus': 'Bananarama',
      'title': 'Cette Année Là #10',
      'subtitle': 'On recherche l\'année de sortie du morceau !',
      'songs': [
        { 'name': '2015', 'alternate': '', 'fullname': '2015 - Alan Walker - Faded', 'youtube': 'https://www.youtube.com/watch?v=qdpXxGPqW-Y' },
        { 'name': '2002', 'alternate': '', 'fullname': '2002 - Bratisla Boys - Stach Stach', 'youtube': 'https://www.youtube.com/watch?v=0mv7ljo9x0g' },
        { 'name': '1992', 'alternate': '', 'fullname': '1992 - Red Hot Chili Peppers - Under the Bridge', 'youtube': 'https://www.youtube.com/watch?v=lwlogyj7nFE' },
        { 'name': '1978', 'alternate': '', 'fullname': '1978 - Daniel Balavoine - Le Chanteur', 'youtube': 'https://www.youtube.com/watch?v=HXdP15Ubu6M' },
        { 'name': '1963', 'alternate': '', 'fullname': '1963 - Richard Anthony - Je Suis Trop Loin de Toi', 'youtube': 'https://www.youtube.com/watch?v=TXJnl2RYqGY' },
        { 'name': '1971', 'alternate': '', 'fullname': '1971 - Gérard Palaprat - Pour la fin du monde', 'youtube': 'https://www.youtube.com/watch?v=Q2ZdvTjWUjo' },
        { 'name': '1995', 'alternate': '', 'fullname': '1995 - Neg\'Marrons - La Monnaie', 'youtube': 'https://www.youtube.com/watch?v=R2soq6j21go' },
        { 'name': '2003', 'alternate': '', 'fullname': '2003 - Linkup - Mon Etoile', 'youtube': 'https://www.youtube.com/watch?v=FSUzQaiwVq8' },
        { 'name': '1980', 'alternate': '', 'fullname': '1980 - Irene Cara - Fame', 'youtube': 'https://www.youtube.com/watch?v=e9dEg_JY_N8' },
        { 'name': '1988', 'alternate': '', 'fullname': '1988 - David et Jonathan - Est-ce que tu viens pour les Vacances', 'youtube': 'https://www.youtube.com/watch?v=m0MgGUnLsdo' },
        { 'name': '1966', 'alternate': '', 'fullname': '1966 - Spencer Davis Group - Gimme Some Lovin\'', 'youtube': 'https://www.youtube.com/watch?v=I5cTP8BHhvs' },
        { 'name': '2017', 'alternate': '', 'fullname': '2017 - Indochine - la Vie est Belle', 'youtube': 'https://www.youtube.com/watch?v=besxnNQlqg4' },
      ]
    },
    {
      'listname': 'paroles',
      'type': 'double',
      'done': false,
      'bonus': 'The Temptations',
      'title': 'N\'oubliez pas les paroles #4',
      'info1': 'Interprète',
      'info2': 'Paroles',
      'subtitle': 'N\'oubliez pas les Paroles ! On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) et la fin des paroles !',
      'songs': [
        { 'info': [{ 'name': 'Françoise Hardy', 'alternate': '', 'fullname': 'Françoise Hardy - Mon Amie La Rose' }, { 'name': 'vieille', 'alternate': '', 'fullname': 'vieille' }], 'youtube': 'https://www.youtube.com/watch?v=jA0KjTtsVCc', 'singletext': '1 mot à trouver', },
        { 'info': [{ 'name': 'Adamo', 'alternate': 'Salvatore Adamo', 'fullname': 'Adamo - Mes mains sur tes hanches' }, { 'name': 'grand amour', 'alternate': '', 'fullname': 'grand amour' }], 'youtube': 'https://www.youtube.com/watch?v=dZAPnPDxZV0', 'singletext': '2 mots à trouver', },
        { 'info': [{ 'name': 'Zebda', 'alternate': '', 'fullname': 'Zebda - Tomber la Chemise' }, { 'name': 'en un mot la famille', 'alternate': '', 'fullname': 'en un mot la famille' }], 'youtube': 'https://www.youtube.com/watch?v=4y4D-evzDTo', 'singletext': '5 mots à trouver', },
        { 'info': [{ 'name': 'Boby Lapointe', 'alternate': '', 'fullname': 'Boby Lapointe - La Maman des Poissons' }, { 'name': 'froncer les sourcils', 'alternate': '', 'fullname': 'froncer les sourcils' }], 'youtube': 'https://www.youtube.com/watch?v=caQzV_kD7T4', 'singletext': '3 mots à trouver', },
        { 'info': [{ 'name': 'Indochine', 'alternate': '', 'fullname': 'Indochine - Troisième Sexe' }, { 'name': 'dans une boîte en fer', 'alternate': '', 'fullname': 'dans une boîte en fer' }], 'youtube': 'https://www.youtube.com/watch?v=SWtiCRntA-E', 'singletext': '5 mots à trouver', },
        { 'info': [{ 'name': 'Tryo', 'alternate': '', 'fullname': 'Tryo - L\'Hymne de nos campagnes' }, { 'name': 'faire quelque chose de tes mains', 'alternate': '', 'fullname': 'faire quelque chose de tes mains' }], 'youtube': 'https://www.youtube.com/watch?v=srb0lAK5wbA', 'singletext': '6 mots à trouver', },
        { 'info': [{ 'name': 'Philippe Lavil', 'alternate': '', 'fullname': 'Philippe Lavil - Il Tape sur des Bambous' }, { 'name': 'équateur méridien', 'alternate': '', 'fullname': 'équateur méridien' }], 'youtube': 'https://www.youtube.com/watch?v=ydBmk3jUkhY', 'singletext': '2 mots à trouver', },
        { 'info': [{ 'name': 'Sinsemilia', 'alternate': '', 'fullname': 'Sinsemilia - Tout le Bonheur du Monde' }, { 'name': 'Que votre envol est pour demain', 'alternate': '', 'fullname': 'Que votre envol est pour demain' }], 'youtube': 'https://www.youtube.com/watch?v=dGBQUcQZmYQ', 'singletext': '6 mots à trouver', },
        { 'info': [{ 'name': 'JJ Lionel', 'alternate': 'J.J. Lionel', 'fullname': 'JJ Lionel - La Danse des Canards' }, { 'name': 'Pliez les genoux', 'alternate': '', 'fullname': 'Pliez les genoux' }], 'youtube': 'https://www.youtube.com/watch?v=pXCPx-LMP0w', 'singletext': '3 mots à trouver', },
        { 'info': [{ 'name': 'K Maro', 'alternate': 'K.Maro', 'fullname': 'K Maro - Femme Like U' }, { 'name': 'qui fuit', 'alternate': '', 'fullname': 'qui fuit' }], 'youtube': 'https://www.youtube.com/watch?v=8qfM7offtiA', 'singletext': '2 mots à trouver', },
        { 'info': [{ 'name': 'Maxime Le Forestier', 'alternate': '', 'fullname': 'Maxime Le Forestier - Mon Frère' }, { 'name': 'on se serait battus', 'alternate': '', 'fullname': 'on se serait battus' }], 'youtube': 'https://www.youtube.com/watch?v=CKukjRr68mE', 'singletext': '4 mots à trouver', },
        { 'info': [{ 'name': 'KOD', 'alternate': 'K.O.D.', 'fullname': 'KOD - Chacun sa route' }, { 'name': 'dans les escaliers', 'alternate': '', 'fullname': 'dans les escaliers' }], 'youtube': 'https://www.youtube.com/watch?v=oJ_x1yRyATA', 'singletext': '3 mots à trouver', },
      ]
    },
    {
      'listname': 'selexemple',
      'type': 'sel',
      'done': false,
      //'bonus': 'Salt-N-Pepa',
      'title': 'Sel ou Poivre #1 (Exemple)',
      'subtitle': 'Sel, ou poivre ? Répondez par sel (ou 1 ou S) ou poivre (ou 2 ou P) en moins de 10 secondes !',
      'songs': [
        { 'question': 'Quel est mon surnom ?', 'sel': 'Totoro', 'poivre': 'Tuturu', 'answer': 'sel', 'youtube': 'https://www.youtube.com/watch?v=0qtYnxlLng8' },
        { 'question': 'Qui est le roi du Blindtest ?', 'sel': 'Prince de Lu', 'poivre': 'Prince Yaku', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=Q3Pdw7TPm30' },
      ]
    },
    {
      'listname': 'sel',
      'type': 'sel',
      'done': false,
      'bonus': 'Salt-N-Pepa',
      'title': 'Sel ou Poivre #1 (Nouveau jeu !)',
      'subtitle': 'Sel, ou poivre ? Répondez par sel (ou 1 ou S) ou poivre (ou 2 ou P) en moins de 10 secondes !',
      'songs': [
        { 'question': 'Pink Floyd, en français, ça veut dire Flamant Rose', 'sel': 'Vrai', 'poivre': 'Faux', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=7jMlFXouPk8' },
        { 'question': 'Qui s\'appelle réellement "Shahnour Varenagh Aznavarujian" ?', 'sel': 'Charles Aznavour', 'poivre': 'Richard Anthony', 'answer': 'sel', 'youtube': 'https://www.youtube.com/watch?v=fVfnEyLOkrM' },
        { 'question': 'Qui chante "Pour que tu m\'aimes encore ?"', 'sel': 'Lara Fabian', 'poivre': 'Céline Dion', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=Unk5Tg37aO8' },
        { 'question': 'L\'intégralité des albums studios de Led Zep dure 666 minutes', 'sel': 'Vrai', 'poivre': 'Faux', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=tzVJPgCn-Z8' },
        { 'question': 'Qui s\'appelle réellement "Tamara Marthe" ?', 'sel': 'Shy\'m', 'poivre': 'Tal', 'answer': 'sel', 'youtube': 'https://www.youtube.com/watch?v=2zdqymnZoHc' },
        { 'question': 'Qui chante "A Horse with No Name" ?', 'sel': 'Neil Young', 'poivre': 'America', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=oIYgsqhwXzM' },
        { 'question': 'Qui chante "Bitch" ?', 'sel': 'Alanis Morissette', 'poivre': 'Meredith Brooks', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=zIAku-Qwfl0' },
        { 'question': 'Qui chante "All The Young Dudes" ?', 'sel': 'David Bowie', 'poivre': 'Mott The Hoople', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=yNHdPPJGowY' },
        { 'question': 'Qui chante "G-L-O-R-I-A" ?', 'sel': 'The Rolling Stones', 'poivre': 'Them', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=VlWiQ69DGE0' },
        { 'question': 'Qui chante "Twist and Shout" ?', 'sel': 'The Beatles', 'poivre': 'The Butterfleas', 'answer': 'sel', 'youtube': 'https://www.youtube.com/watch?v=2RicaUqd9Hg' },
        { 'question': 'Dans Starmania, Marie-Jeanne dit "J\'voudrais...', 'sel': 'Seule m\'endormir', 'poivre': 'Seulement dormir', 'answer': 'poivre', 'youtube': 'https://www.youtube.com/watch?v=Agd0y1n_nhs' },
        { 'question': 'On dit Portichèd ou Portissède ?', 'sel': 'Portissède', 'poivre': 'Portichède', 'answer': 'sel', 'youtube': 'https://www.youtube.com/watch?v=4qQyUi4zfDs' },
      ]
    },
    {
      'listname': 'djexemple',
      'type': 'djviewers',
      'done': false,
      'title': 'DJ Viewers #1 (Exemple)',
      'subtitle': 'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) des extraits courts !',
      'songs': [
        { 'name': 'Annie Cordy', 'alternate': '', 'fullname': 'Annie Cordy - Tata Yoyo', 'samples': 153, 'youtube': 'https://www.youtube.com/watch?v=T9kadX9SWho' },
      ]
    },
    {
      'listname': 'djviewers',
      'type': 'djviewers',
      'done': false,
      'bonus': 'Martin Solveig',
      'title': 'DJ Viewers #1 (Nouveau jeu !)',
      'subtitle': 'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) des extraits courts !',
      'songs': [
        { 'name': 'William Sheller', 'alternate': '', 'fullname': 'William Sheller - Un Homme Heureux', 'samples': 225, 'youtube': 'https://www.youtube.com/watch?v=R1wAXsbVlHE' },
        { 'name': 'Childish Gambino', 'alternate': '', 'fullname': 'Childish Gambino - This is America', 'samples': 241, 'youtube': 'https://www.youtube.com/watch?v=VYOjWnS4cMY' },
        { 'name': 'Gorillaz', 'alternate': '', 'fullname': 'Gorillaz - Feel Good Inc.', 'samples': 222, 'youtube': 'https://www.youtube.com/watch?v=dKez38i5h14' },
        { 'name': 'Eric Clapton', 'alternate': '', 'fullname': 'Eric Clapton - Wonderful Tonight', 'samples': 221, 'youtube': 'https://www.youtube.com/watch?v=Pu5c4aEg3NM' },
        { 'name': 'Juanes', 'alternate': '', 'fullname': 'Juanes - La Camisa Negra', 'samples': 217, 'youtube': 'https://www.youtube.com/watch?v=7fwUH0oRmkQ' },
        { 'name': 'Clara Luciani', 'alternate': '', 'fullname': 'Clara Luciani - La Grenade', 'samples': 190, 'youtube': 'https://www.youtube.com/watch?v=85m-Qgo9_nE' },
        { 'name': 'Johnny Cash', 'alternate': '', 'fullname': 'Johnny Cash - Hurt', 'samples': 229, 'youtube': 'https://www.youtube.com/watch?v=8AHCfZTRGiI' },
        { 'name': 'Tryo', 'alternate': '', 'fullname': 'Tryo - Désolé pour Hier Soir', 'samples': 218, 'youtube': 'https://www.youtube.com/watch?v=dYkeH5UVw8U' },
        { 'name': 'Khaled', 'alternate': '', 'fullname': 'Khaled - Aicha', 'samples': 263, 'youtube': 'https://www.youtube.com/watch?v=Peklmy6CFbg' },
        { 'name': 'Manu Chao', 'alternate': '', 'fullname': 'Manu Chao - Me Gustas Tu', 'samples': 240, 'youtube': 'https://www.youtube.com/watch?v=rs6Y4kZ8qtw' },
        { 'name': 'Ricky Martin', 'alternate': '', 'fullname': 'Ricky Martin - Livin La Vida Loca', 'samples': 244, 'youtube': 'https://www.youtube.com/watch?v=CN5hQOI__10' },
        { 'name': 'Yes', 'alternate': '', 'fullname': 'Yes - Owner of a Lonely Heart', 'samples': 269, 'youtube': 'https://www.youtube.com/watch?v=IG_VDj8Eh_g' },
      ]
    },
    {
      'listname': 'mystere',
      'type': 'single',
      'done': false,
      'bonus': 'The Chemical Brothers',
      'title': 'Thème mystère',
      'subtitle': 'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) et le lien qui les unit !',
      'songs': [
        { 'name': 'Supergrass', 'alternate': '', 'fullname': 'Supergrass - Alright', 'youtube': 'https://www.youtube.com/watch?v=SJRyMnKuJDg' },
        { 'name': 'Ménélik', 'alternate': '', 'fullname': 'Ménélik - Quelle Aventure', 'youtube': 'https://www.youtube.com/watch?v=CCO5DiwvJm8' },
        { 'name': 'Garbage', 'alternate': '', 'fullname': 'Garbage - Only Happy when it Rains', 'youtube': 'https://www.youtube.com/watch?v=83o1eAS7eiY' },
        { 'name': 'PJ Harvey', 'alternate': '', 'fullname': 'PJ Harvey - Down by the Water', 'youtube': 'https://www.youtube.com/watch?v=lbq4G1TjKYg' },
        { 'name': 'Alliance Ethnik', 'alternate': '', 'fullname': 'Alliance Ethnik - Honesty & Jalousie', 'youtube': 'https://www.youtube.com/watch?v=MSdeCxDiI5o' },
        { 'name': 'Zazie', 'alternate': '', 'fullname': 'Zazie - Larsen', 'youtube': 'https://www.youtube.com/watch?v=8WELZT4_P4Y' },
        { 'name': 'Oasis', 'alternate': '', 'fullname': 'Oasis - Don\'t Look Back in Anger', 'youtube': 'https://www.youtube.com/watch?v=4G1BFFcEgpc' },
        { 'name': 'Alanis Morissette', 'alternate': '', 'fullname': 'Alanis Morissette - You Learn', 'youtube': 'https://www.youtube.com/watch?v=GFW-WfuX2Dk' },
        { 'name': 'Smashing Pumpkins', 'alternate': '', 'fullname': 'Smashing Pumpkins - 1979', 'youtube': 'https://www.youtube.com/watch?v=4aeETEoNfOg' },
        { 'name': 'Les Innocents', 'alternate': '', 'fullname': 'Les Innocents - Colore', 'youtube': 'https://www.youtube.com/watch?v=xijx0goAGRQ' },
        { 'name': 'La Bouche', 'alternate': '', 'fullname': 'La Bouche - Be My Lover', 'youtube': 'https://www.youtube.com/watch?v=NruQh0QDTTM' },
        { 'name': 'Maxime Le Forestier', 'alternate': '', 'fullname': 'Maxime Le Forestier - Passer ma Route', 'youtube': 'https://www.youtube.com/watch?v=B6kbh4h0D4Q' },
      ]
    },
    {
      'listname': 'collab',
      'type': 'collab',
      'done': false,
      'nbwin': 100,
      'title': 'Shoot Richard',
      'subtitle': 'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) des extraits courts !',
      'songs': [
        {
          'name': 'Passi', 'alternate': '', 'fullname': 'Passi - Evolution', 'youtube': 'https://www.youtube.com/watch?v=wlcco0EWvQ8', 'songs': [
            { 'name': 'The Police', 'alternate': 'Police', 'fullname': 'The Police - Message in a Bottle', 'youtube': 'https://www.youtube.com/watch?v=MbXWrmQW-OE', 'found': false, 'rank': 12 },
            { 'name': 'Pink Floyd', 'alternate': '', 'fullname': 'Pink Floyd - Money', 'youtube': 'https://www.youtube.com/watch?v=-0kcet4aPpQ', 'found': false, 'rank': 24 },
            { 'name': 'Pixies', 'alternate': '', 'fullname': 'Pixies - Where is My Mind', 'youtube': 'https://www.youtube.com/watch?v=49FB9hhoO6c', 'found': false, 'rank': 11 },
            { 'name': 'Placebo', 'alternate': '', 'fullname': 'Placebo - The Bitter End', 'youtube': 'https://www.youtube.com/watch?v=0W9jyRm7xHo', 'found': false, 'rank': 18 },
            { 'name': 'Portishead', 'alternate': '', 'fullname': 'Portishead - Glory Box', 'youtube': 'https://www.youtube.com/watch?v=4qQyUi4zfDs', 'found': false, 'rank': 17 },
            { 'name': 'Pretenders', 'alternate': '', 'fullname': 'Pretenders - I\'ll Stand By you', 'youtube': 'https://www.youtube.com/watch?v=MlfP5QuPhno', 'found': false, 'rank': 23 },
            { 'name': 'Le Peuple de l\'Herbe', 'alternate': 'Peuple de l\'Herbe', 'fullname': 'Le Peuple de l\'Herbe - PH Theme', 'youtube': 'https://www.youtube.com/watch?v=ID-xAbCjLfs', 'found': false, 'rank': 22 },
            { 'name': 'The Pogues', 'alternate': 'Pogues', 'fullname': 'The Pogues - Dirty Old Town', 'youtube': 'https://www.youtube.com/watch?v=s11BuatTuXk', 'found': false, 'rank': 9 },
            { 'name': 'The Pussycat Dolls', 'alternate': 'Pussycat Dolls', 'fullname': 'The Pussycat Dolls - Don\'t Cha', 'youtube': 'https://www.youtube.com/watch?v=IbRkSjYgSmI', 'found': false, 'rank': 15 },
            { 'name': 'Passenger', 'alternate': '', 'fullname': 'Passenger - Let Her Go', 'youtube': 'https://www.youtube.com/watch?v=RBumgq5yVrA', 'found': false, 'rank': 10 },
            { 'name': 'Prince', 'alternate': '', 'fullname': 'Prince - Purple Rain', 'youtube': 'https://www.youtube.com/watch?v=S6Y1gohk5-A', 'found': false, 'rank': 2 },
            { 'name': 'Pink Martini', 'alternate': '', 'fullname': 'Pink Martini - Sympathique', 'youtube': 'https://www.youtube.com/watch?v=nLaY4aksfRo', 'found': false, 'rank': 16 },
            { 'name': 'The Presidents of the USA', 'alternate': 'Presidents of the USA', 'fullname': 'The Presidents of the USA - Lump', 'youtube': 'https://www.youtube.com/watch?v=RYyo1eB8f4c', 'found': false, 'rank': 20 },
            { 'name': 'The Prodigy', 'alternate': 'Prodigy', 'fullname': 'The Prodigy - Firestarter', 'youtube': 'https://www.youtube.com/watch?v=wmin5WkOuPw', 'found': false, 'rank': 6 },
            { 'name': 'Portugal. The Man', 'alternate': '', 'fullname': 'Portugal. The Man - Fill It Still', 'youtube': 'https://www.youtube.com/watch?v=OPKTk5vUtDY', 'found': false, 'rank': 7 },
            { 'name': 'Parliament', 'alternate': '', 'fullname': 'Parliament - Give Up The Funk (Tear The Roof Off The Sucker)', 'youtube': 'https://www.youtube.com/watch?v=gBWH3OWfT2Y', 'found': false, 'rank': 14 },
            { 'name': 'PNL', 'alternate': '', 'fullname': 'PNL - Au DD', 'youtube': 'https://www.youtube.com/watch?v=BtyHYIpykN0', 'found': false, 'rank': 5 },
            { 'name': 'Panic! at the Disco', 'alternate': 'Panic at the Disco', 'fullname': 'Panic at the Disco - High Hopes', 'youtube': 'https://www.youtube.com/watch?v=IPXIgEAGe4U', 'found': false, 'rank': 3 },
            { 'name': 'Psy', 'alternate': '', 'fullname': 'Psy - Gangnam Style', 'youtube': 'https://www.youtube.com/watch?v=9bZkp7q19f0', 'found': false, 'rank': 13 },
            { 'name': 'Poppys', 'alternate': '', 'fullname': 'Poppys - Non Non Rien n\'a changé', 'youtube': 'https://www.youtube.com/watch?v=qVTuV7RRMxU', 'found': false, 'rank': 4 },
            { 'name': 'Procol Harum', 'alternate': '', 'fullname': 'Procol Harum - A Whiter Shade of Pale', 'youtube': 'https://www.youtube.com/watch?v=zLi0gguAO9o', 'found': false, 'rank': 19 },
            { 'name': 'Pigalle', 'alternate': '', 'fullname': 'Pigalle - Dans la Salle du Bar-Tabac de la Rue des Martyrs', 'youtube': 'https://www.youtube.com/watch?v=I5CD0AbpXxQ', 'found': false, 'rank': 21 },
            { 'name': 'Partenaire Particulier', 'alternate': '', 'fullname': 'Partenaire Particulier - Partenaire Particulier', 'youtube': 'https://www.youtube.com/watch?v=NiDkzQgrQIw', 'found': false, 'rank': 8 },
            { 'name': 'Pierpoljak', 'alternate': '', 'fullname': 'Pierpoljak - J\'sais pas jouer', 'youtube': 'https://www.youtube.com/watch?v=B4UhOjS4ero', 'found': false, 'rank': 1 },
            { 'name': 'Pomme', 'alternate': '', 'fullname': 'Pomme - On Brûlera', 'youtube': 'https://www.youtube.com/watch?v=jabih9mV6RQ', 'found': false, 'rank': 0 },
          ]
        },
      ]
    },

  ];