// eslint-disable-next-line no-unused-vars
var songlist = 
[
{
    'listname':'exemple',
    'done':false,
    'theme':'Exemple',
    'type':'single',
    'title':'Exemple',
    'subtitle':'On fait un test pour du beurre (avec des sagas cultes) !',
    'songs': [
        {'name':'Harry Potter','alternate':'','fullname':'Harry Potter - Hedwig\'s Theme','youtube':'https://www.youtube.com/watch?v=wtHra9tFISY'},
        {'name':'Star Wars','alternate':'','fullname':'Star Wars - Duel of the Fates','youtube':'https://www.youtube.com/watch?v=-vzvCRCU82g'},
        {'name':'Jurassic Park','alternate':'','fullname':'Jurassic Park - Welcome to Jurassic Park','youtube':'https://www.youtube.com/watch?v=BXsWn9DhF5g'},
    ]
},
{
    'listname':'journee',
    'type':'single',
    'done':false,
    'title':'Spécial XMas',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Bob Dylan','alternate':'','fullname':'Bob Dylan - Here Comes Santa Claus','youtube':'https://www.youtube.com/watch?v=bOaZ96kr1WM'},
        {'name':'James Brown','alternate':'','fullname':'James Brown - Santa Claus Go Straight to the Ghetto','youtube':'https://www.youtube.com/watch?v=Aur9gLzsXQU'},
        {'name':'Queen','alternate':'','fullname':'Queen - Thank God It\'s Christmas','youtube':'https://www.youtube.com/watch?v=qw2TD91Nytg'},
        {'name':'Jackson 5','alternate':'Jackson Five','fullname':'Jackson 5 - I Saw Mommy Kissing Santa Claus','youtube':'https://www.youtube.com/watch?v=U5resSXzMiI'},
        {'name':'The Ramones','alternate':'Ramones','fullname':'The Ramones - Merry Christmas (I Don\'t Want to Fight Tonight) ','youtube':'https://www.youtube.com/watch?v=KIhIBFPtnoc'},
        {'name':'Spice Girls','alternate':'','fullname':'Spice Girls - Christmas Wrapping','youtube':'https://www.youtube.com/watch?v=lmI7hPBfm30'},
        {'name':'Garou','alternate':'','fullname':'Garou - Petit Papa Noël','youtube':'https://www.youtube.com/watch?v=cpvhDjGyBS8'},
        {'name':'Joni Mitchell','alternate':'','fullname':'Joni Mitchell - River','youtube':'https://www.youtube.com/watch?v=ozn8UJvrLhU'},
        {'name':'Aretha Franklin','alternate':'','fullname':'Aretha Franklin - Joy To The World','youtube':'https://www.youtube.com/watch?v=q2Ag5MgcDVc'},
        {'name':'The Beach Boys','alternate':'Beach Boys','fullname':'The Beach Boys - Little Saint Nick','youtube':'https://www.youtube.com/watch?v=AbgxDgVmMF0'},
        {'name':'TLC','alternate':'','fullname':'TLC - Sleigh Ride','youtube':'https://www.youtube.com/watch?v=62rmjtZdCv8'},
        {'name':'Hanson','alternate':'','fullname':'Hanson - Merry Christmas Baby','youtube':'https://www.youtube.com/watch?v=-OfxPUEh9Pg'},        
    ]
},
{
    'listname':'year',
    'done':false,
    'type':'year',
    'title':'What year is it ?! #2',
    'subtitle':'On recherche l\'année de sortie du titre !',
    'songs': [
        {'name':'2008','alternate':'','fullname':'Pink - So What','youtube':'https://www.youtube.com/watch?v=BQ2P1K7Yl00'},
        {'name':'1976','alternate':'','fullname':'ABBA - Dancing Queen','youtube':'https://www.youtube.com/watch?v=xFrGuyw1V8s'},
        {'name':'1964','alternate':'','fullname':'Roy Orbison - Pretty Woman','youtube':'https://www.youtube.com/watch?v=3KFvoDDs0XM'},
        {'name':'1996','alternate':'','fullname':'The Cardigans - Lovefool','youtube':'https://www.youtube.com/watch?v=NI6aOFI7hms'},
        {'name':'2005','alternate':'','fullname':'Gwen Stefani - Hollaback Girl','youtube':'https://www.youtube.com/watch?v=r2AqGffHuZI'},
        {'name':'1997','alternate':'','fullname':'Eagle-Eye Cherry - Save Tonight','youtube':'https://www.youtube.com/watch?v=Nntd2fgMUYw'},
        {'name':'1983','alternate':'','fullname':'Elton John - I\'m Still Standing','youtube':'https://www.youtube.com/watch?v=ZHwVBirqD2s'},
        {'name':'1967','alternate':'','fullname':'Bobbie Gentry - Ode to Billie Joe','youtube':'https://www.youtube.com/watch?v=cJZ_ViDADOE'},
        {'name':'1980','alternate':'','fullname':'Queen - Another one bites the Dust','youtube':'https://www.youtube.com/watch?v=rY0WxgSXdEE'},
        {'name':'2015','alternate':'','fullname':'Major Lazer - Lean On','youtube':'https://www.youtube.com/watch?v=YqeW9_5kURI'},
        {'name':'1974','alternate':'','fullname':'Lynyrd Skynyrd - Sweet Home Alabama','youtube':'https://www.youtube.com/watch?v=iL-jC7XyLeo'},
        {'name':'2011','alternate':'','fullname':'Gotye - Somebody that I Used to Know','youtube':'https://www.youtube.com/watch?v=8UVNT4wvIGY'},
    ]
},
{
    'listname':'acappella',
    'type':'single',
    'done':false,
    'title':'A Cappella',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) de cette reprise a cappella !',
    'songs': [
        {'name':'Mark Ronson','alternate':'','fullname':'Mark Ronson - Uptown Funk','youtube':'https://www.youtube.com/watch?v=3er8ytNbT2A'},
        {'name':'Stromae','alternate':'','fullname':'Stromae - Papaoutai (QW4RTZ)','youtube':'https://www.youtube.com/watch?v=a4mEKN8VsiE'},
        {'name':'Fleetwood Mac','alternate':'','fullname':'Fleetwood Mac - Dreams (KOLA)','youtube':'https://www.youtube.com/watch?v=xQRUlk6IoXE'},
        {'name':'Mickael Jackson','alternate':'','fullname':'Mickael Jackson - They Don\'t Care About Us (DeStorm)','youtube':'https://www.youtube.com/watch?v=8eaGuzog59c'},
        {'name':'Sia','alternate':'','fullname':'Sia - Cheap Thrills (Indy Dang)','youtube':'https://www.youtube.com/watch?v=spFfNsC2Qy0'},
        {'name':'Linkin Park','alternate':'','fullname':'Linkin Park - Numb/In The End (The Buzztones)','youtube':'https://www.youtube.com/watch?v=sK9PKwGqp5A'},
        {'name':'Don McLean','alternate':'','fullname':'Don McLean - American Pie (Anne Reburn)','youtube':'https://www.youtube.com/watch?v=hvvVd_ikaCc'},
        {'name':'a-ha','alternate':'haha','fullname':'a-ha - Take On Me (Jared Halley)','youtube':'https://www.youtube.com/watch?v=AmsMkwcWPZ0'},
        {'name':'Eurythmics','alternate':'','fullname':'Eurythmics - Sweet Dreams (Holly Henry)','youtube':'https://www.youtube.com/watch?v=hjJOQ7bBfCs'},
        {'name':'Manau','alternate':'','fullname':'Manau - La Tribu de Dana (QW4RTZ)','youtube':'https://www.youtube.com/watch?v=BJmAzV0rckY'},
        {'name':'Dolly Parton','alternate':'','fullname':'Dolly Parton - Jolene (Haven)','youtube':'https://www.youtube.com/watch?v=1jaJQfvfodA'},
        {'name':'The Mamas and the Papas','alternate':'The Mamas & the papas','fullname':'The Mamas and the Papas - California Dreaming','youtube':'https://twitch.tv/totorophd'},
        ]
},
{
    'listname':'trad',
    'type':'single',
    'done':false,
    'title':'Google Traduction',
    'subtitle':'On recherche le (pré)nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Avril Lavigne','alternate':'','fullname':'Avril Lavigne - Sk8ter Boi','youtube':'https://www.youtube.com/watch?v=TIy3n2b7V9k'},
        {'name':'Portishead','alternate':'','fullname':'Portishead - Glorybox','youtube':'https://www.youtube.com/watch?v=4qQyUi4zfDs'},
        {'name':'The Rolling Stones','alternate':'Rolling Stones','fullname':'The Rolling Stones - Sympathy for the Devil','youtube':'https://www.youtube.com/watch?v=GgnClrx8N2k'},
        {'name':'Lady Gaga','alternate':'','fullname':'Lady Gaga - Bad Romance','youtube':'https://www.youtube.com/watch?v=qrO4YZeyl0I'},
        {'name':'Oasis','alternate':'','fullname':'Oasis - Wonderwall','youtube':'https://www.youtube.com/watch?v=bx1Bh8ZvH84'},
        {'name':'Pink Floyd','alternate':'','fullname':'Pink Floyd - Brain Damage','youtube':'https://www.youtube.com/watch?v=BhYKN21olBw'},
        {'name':'U2','alternate':'','fullname':'U2 - With or Without You','youtube':'https://www.youtube.com/watch?v=ujNeHIo7oTE'},
        {'name':'Katy Perry','alternate':'','fullname':'Katy Perry - I Kissed a Girl','youtube':'https://www.youtube.com/watch?v=usvTbqTHwyw'},
        {'name':'Queen','alternate':'','fullname':'Queen - We are the Champions','youtube':'https://www.youtube.com/watch?v=04854XqcfCY'},
        {'name':'Cyndi Lauper','alternate':'','fullname':'Cyndi Lauper - Girls just want to have Fun','youtube':'https://www.youtube.com/watch?v=PIb6AZdTr-A'},
        {'name':'Billie Eilish','alternate':'','fullname':'Billie Eilish - Bad Guy','youtube':'https://www.youtube.com/watch?v=DyDfgMOUjCI'},
        {'name':'Nirvana','alternate':'','fullname':'Nirvana - Smells like Teen Spirit','youtube':'https://www.youtube.com/watch?v=hTWKbfoikeg'},        
    ]
},
{
    'listname':'choke',
    'type':'single',
    'done':false,
    'lev':0.90,
    'title':'Pinjks Floydsf',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Sixpence None the Ritcher','alternate':'','fullname':'Sixpenth None the Ritcher - Kiss Me','youtube':'https://www.youtube.com/watch?v=zlEMp315cNQ'},
        {'name':'Creedance Clearwater Revival','alternate':'','fullname':'Creedance Clearwater Revival - Fortunate Son','youtube':'https://www.youtube.com/watch?v=ZWijx_AgPiA'},
        {'name':'Huey Lewis and the News','alternate':'','fullname':'Huey Lewis and the News - Power of Love','youtube':'https://www.youtube.com/watch?v=CyFXdIl00y8'},
        {'name':'Siouxsie and The Banshees','alternate':'','fullname':'Siouxsie and The Banshees - Spellbound','youtube':'https://www.youtube.com/watch?v=TjvvK-Rj0WI'},
        {'name':'Dexys Midnight Runners','alternate':'','fullname':'Dexys Midnight Runners - Come on Eileen','youtube':'https://www.youtube.com/watch?v=HwVnX4ZgliY'},
        {'name':'Sly and the Family Stone','alternate':'','fullname':'Sly and the Family Stone - Everyday People','youtube':'https://www.youtube.com/watch?v=YUUhDoCx8zc'},
        {'name':'Big Brother and the Holding Company','alternate':'','fullname':'Big Brother and the Holding Company - Summertime','youtube':'https://www.youtube.com/watch?v=A24JZkgvNv4'},
        {'name':'Red Hot Chili Peppers','alternate':'','fullname':'Red Hot Chili Peppers - Under the Bridge','youtube':'https://www.youtube.com/watch?v=GLvohMXgcBo'},
        {'name':'Derek and the Dominos','alternate':'','fullname':'Derek and the Dominos - Layla','youtube':'https://www.youtube.com/watch?v=tBTJ3W06Eeg'},
        {'name':'Crosby Stills Nash & Young','alternate':'','fullname':'Crosby Stills Nash & Young - Carry On','youtube':'https://www.youtube.com/watch?v=lh67x9iDCjg'},
        {'name':'The Velvet Underground','alternate':'Velvet Underground','fullname':'The Velvet Underground and Nico - Sunday Morning','youtube':'https://www.youtube.com/watch?v=Xhbyj8pqUao'},
        {'name':'Florence + The Machine','alternate':'Florence and the Machine','fullname':'Florence + The Machine - You\'ve Got The Love','youtube':'https://www.youtube.com/watch?v=PQZhN65vq9E'},        
    ]
},
{
    'listname':'litterature',
    'type':'single',
    'done':false,
    'title':'Thème mystère',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Supertramp','alternate':'','fullname':'Supertramp - Give a Little Bit','youtube':'https://www.youtube.com/watch?v=J9JOut9yh5g'},
        {'name':'Mott the Hoople','alternate':'','fullname':'Mott the Hoople - All The Young Dudes','youtube':'https://www.youtube.com/watch?v=yNHdPPJGowY'},
        {'name':'Coldplay','alternate':'','fullname':'Coldplay - Yellow','youtube':'https://www.youtube.com/watch?v=yKNxeF4KMsY'},
        {'name':'Steppenwolf','alternate':'','fullname':'Steppenwolf - The Pusher','youtube':'https://www.youtube.com/watch?v=Np7x0KgLet0'},
        {'name':'The Doors','alternate':'Doors','fullname':'The Doors - Roadhouse Blues','youtube':'https://www.youtube.com/watch?v=yV9DJwJKWMw'},
        {'name':'Joy Division','alternate':'','fullname':'Joy Division - Love Will Tear Us Apart','youtube':'https://www.youtube.com/watch?v=aYCshYyFzls'},
        {'name':'The Velvet Underground','alternate':'Velvet Underground','fullname':'The Velvet Underground - Pale Blue Eyes','youtube':'https://www.youtube.com/watch?v=MA3aKUwu-Dk'},
        {'name':'Genesis','alternate':'','fullname':'Genesis - For Absent Friends','youtube':'https://www.youtube.com/watch?v=BHus88oxvLE'},
        {'name':'Belle & Sebastian','alternate':'','fullname':'Belle & Sebastian - Piazza, New York Catcher','youtube':'https://www.youtube.com/watch?v=MUusqP5GLtU'},
        {'name':'Tears for Fears','alternate':'','fullname':'Tears for Fears - Shout','youtube':'https://www.youtube.com/watch?v=Ye7FKc1JQe4'},
        {'name':'Moby','alternate':'','fullname':'Moby - Lift me Up','youtube':'https://www.youtube.com/watch?v=JwTmigSD7t4'},
        {'name':'Good Charlotte','alternate':'','fullname':'Good Charlotte - The Anthem','youtube':'https://www.youtube.com/watch?v=desJKYvdq9A'},        
    ]
},
{
    'listname':'collab',
    'type':'collab',
    'done':false,
    'nbwin':100,
    'title':'Shoot Richard #5',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) des extraits courts !',
    'songs': [
        {'name':'Richard Anthony','alternate':'','fullname':'Richard Anthony chante Noël','youtube':'https://www.youtube.com/watch?v=WDZYr3yXWsQ','songs':[
            {'name':'Toto','alternate':'','found':'false','rank':15},
            {'name':'Alizée','alternate':'','found':'false','rank':24},
            {'name':'Simon & Garfunkel','alternate':'Simon and Garfunkel','found':'false','rank':0},
            {'name':'Fernandel','alternate':'','found':'false','rank':16},
            {'name':'The Beatles','alternate':'Beatles','found':'false','rank':22},
            {'name':'Joe Dassin','alternate':'','found':'false','rank':4},
            {'name':'Kaiser Chiefs','alternate':'','found':'false','rank':8},
            {'name':'Saïan Supa Crew','alternate':'','found':'false','rank':17},
            {'name':'Elmer Food Beat','alternate':'','found':'false','rank':5},
            {'name':'Les Cowboys Fringants','alternate':'Cowboys Fringants','found':'false','rank':19},
            {'name':'Georges Brassens','alternate':'','found':'false','rank':7},
            {'name':'Them','alternate':'Van Morrison','found':'false','rank':23},
            {'name':'The Rolling Stones','alternate':'Rolling Stones','found':'false','rank':14},
            {'name':'Tom Jones','alternate':'','found':'false','rank':21},
            {'name':'Michel Delpech','alternate':'','found':'false','rank':9},
            {'name':'Alain Bashung','alternate':'','found':'false','rank':10},
            {'name':'Serge Gainsbourg','alternate':'','found':'false','rank':2},
            {'name':'Pascal Obispo','alternate':'','found':'false','rank':6},
            {'name':'Dave','alternate':'','found':'false','rank':20},
            {'name':'Matmatah','alternate':'','found':'false','rank':18},
            {'name':'Gilbert Bécaud','alternate':'','found':'false','rank':11},
            {'name':'Leonard Cohen','alternate':'','found':'false','rank':12},
            {'name':'Pierre Perret','alternate':'','found':'false','rank':3},
            {'name':'The Turtles','alternate':'Turtles','found':'false','rank':13},
            {'name':'Francis Cabrel','alternate':'','found':'false','rank':1},            
        ]},  
    ]
},
{
    'listname':'trivial',
    'done':false,
    'type':'trivial',
    'title':'Trivial Pour Suite #5',
    'subtitle':'Débloquez des instruments en répondant aux questions ! On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'The Byrds','alternate':'Byrds','fullname':'The Byrds - Mr. Tambourine Man','youtube':'https://www.youtube.com/watch?v=Swqw5a8I4b4','quiz':[
            {'category':'GEO','question':'En 2014, combien de fromages français avaient une Appellation d\'Origine Contrôlée (AOC) ?','answer':'26','alternate':'','found':'false','lev':1},
            {'category':'DIV','question':'Quel acteur incarne Dawson dans la série télévisée du même nom ?','answer':'James Van Der Beek','alternate':'','found':'false','lev':0.75},
            {'category':'HIS','question':'Quel héros écossais Mel Gibson incarna-t-il dans Braveheart en 1995 ?','answer':'William Wallace','alternate':'','found':'false','lev':0.75},
            {'category':'SCI','question':'Quelle est la plus petite planète de notre système solaire ?','answer':'Mercure','alternate':'','found':'false','lev':0.75},
        ]},
        {'name':'Madonna','alternate':'','fullname':'Madonna - Like a Virgin','youtube':'https://www.youtube.com/watch?v=UHXGc2oWyJ4','quiz':[
            {'category':'ART','question':'Quel est le prénom de la bien-aimée de Don Quichotte ?','answer':'Dulcinée','alternate':'','found':'false','lev':0.75},
            {'category':'SPL','question':'Quel chanteur et acteur français, auteur de Casser la voix et Alors regarde, est aussi un joueur de poker ?','answer':'Patrick Bruel','alternate':'','found':'false','lev':0.75},
            {'category':'GEO','question':'En Europe, quelle langue utilise le mot « agur » pour dire « au revoir » ou « bonjour » ?','answer':'Le Basque','alternate':'Basque','found':'false','lev':0.75},
            {'category':'DIV','question':'Quel auteur-compositeur a écrit Là-Bas et la bande originale du film Astérix et Obélix contre César ?','answer':'Jean-Jacques Goldman','alternate':'','found':'false','lev':0.75},
        ]},
        {'name':'The Police','alternate':'Police','fullname':'The Police - Don\'t Stand So Close to Me','youtube':'https://www.youtube.com/watch?v=EuuX_t3c_2A','quiz':[
            {'category':'HIS','question':'Quel inventeur fut surnommé le sorcier de Menlo Park ?','answer':'Thomas Edison','alternate':'Edison','found':'false','lev':0.75},
            {'category':'SCI','question':'Quelle est la somme de deux côtés opposés d\'un dé normal à six faces ?','answer':'7','alternate':'Sept','found':'false','lev':1},
            {'category':'ART','question':'Quel festival a lieu chaque année à Carhaix ?','answer':'Les Vieilles Charrues','alternate':'Vieilles Charrues','found':'false','lev':0.75},
            {'category':'SPL','question':'Quel chanteur français a chanté Flo pour Florence Arthaud et Le Voilier noir en hommage à Éric Tabarly ?','answer':'Pierre Bachelet','alternate':'','found':'false','lev':0.75},
        ]},
        {'name':'De Palmas','alternate':'','fullname':'De Palmas - Une Seule Vie','youtube':'https://www.youtube.com/watch?v=cn05UMpoXvA','quiz':[
            {'category':'GEO','question':'Le désert de Gobi couvre une partie de la Mongolie et de quel autre pays ?','answer':'Chine','alternate':'','found':'false','lev':0.75},
            {'category':'DIV','question':'Quel chanteur annonce dans l\'album Repenti qu\'il a « toujours préféré aux voisins les voisines » ?','answer':'Renan Luce','alternate':'','found':'false','lev':0.75},
            {'category':'HIS','question':'Quel joaillier créait des œufs émaillés d\'or et de pierres précieuses pour les tsars de Russie ?','answer':'Pierre-Karl Fabergé','alternate':'Fabergé','found':'false','lev':0.75},
            {'category':'SCI','question':'Quelle glande du cerveau, de la taille d\'un petit pois, régule les hormones ?','answer':'L\'Hypophyse','alternate':'Hypophyse','found':'false','lev':0.75},
        ]},        
        {'name':'Les Innocents','alternate':'Innocent','fullname':'Les Innocents - Colore','youtube':'https://www.youtube.com/watch?v=xijx0goAGRQ','quiz':[
            {'category':'ART','question':'Quel grand film classique de 1941 avec Humphrey Bogart est tiré d\'un roman policier de Dashiell Hammett ?','answer':'Le Faucon Maltais','alternate':'Faucon Maltais','found':'false','lev':0.75},
            {'category':'SPL','question':'Quel coureur automobile français a remporté 9 titres consécutifs en championnat du monde des rallyes ?','answer':'Sébastien Loeb','alternate':'','found':'false','lev':0.75},
            {'category':'GEO','question':'Dans quelle ville Chuck Norris affronte-t-il Bruce Lee dans le film La Fureur du dragon ?','answer':'Rome','alternate':'','found':'false','lev':0.75},
            {'category':'DIV','question':'Quel duo présente le SAV des émissions sur Canal + ?','answer':'Omar et Fred','alternate':'Omar & Fred','found':'false','lev':0.75},
        ]},                
        {'name':'Léopold Nord & Vous','alternate':'Léopold Nord et Vous','fullname':'Léopold Nord & Vous - C\'est l\'amour','youtube':'https://www.youtube.com/watch?v=xnvIYpiG5ws','quiz':[
            {'category':'HIS','question':'Quel maréchal de France et compagnon d\'armes de Jeanne d\'Arc a parfois été surnommé Barbe Bleue ?','answer':'Gilles de Rais','alternate':'','found':'false','lev':0.75},
            {'category':'SCI','question':'Quelle partie de leur corps les criquets mâles utilisent-ils pour chanter ?','answer':'Les Ailes','alternate':'ailes','found':'false','lev':0.75},
            {'category':'ART','question':'Quel hebdomadaire satirique français paraît tous les mercredis depuis 1915 ?','answer':'Le Canard Enchaîné','alternate':'Canard Enchaîné','found':'false','lev':0.75},
            {'category':'SPL','question':'Quel coureur cycliste est monté huit fois sur le podium du Tour de France, sans jamais décrocher la victoire ?','answer':'Raymond Poulidor','alternate':'Poulidor','found':'false','lev':0.75},
        ]},                
        {'name':'The Beach Boys','alternate':'Beach Boys','fullname':'The Beach Boys - Good Vibrations','youtube':'https://www.youtube.com/watch?v=oMfjgQ8ptrE','quiz':[
            {'category':'GEO','question':'Dans quelle ville a été ouvert le premier Hard Rock Café en 1971 ?','answer':'Londres','alternate':'','found':'false','lev':0.75},
            {'category':'DIV','question':'Quel est le nom du chat de Gargamel dans Les Schtroumpfs ?','answer':'Azraël','alternate':'Azrael','found':'false','lev':0.75},
            {'category':'HIS','question':'Quel ministre de la Culture a créé la fête de la musique ?','answer':'Jack Lang','alternate':'','found':'false','lev':0.75},
            {'category':'SCI','question':'Quelle plante aromatique originaire du sud de l\'Inde est utilisée traditionnellement pour repousser les moustiques ?','answer':'La Citronnelle','alternate':'Citronnelle','found':'false','lev':0.75},
        ]},                
        {'name':'Savage Garden','alternate':'','fullname':'Savage Garden - Truly Madly Deeply','youtube':'https://www.youtube.com/watch?v=WQnAxOQxQIU','quiz':[
            {'category':'ART','question':'Quel livre de Maurice Sendak a été adapté en long-métrage par Spike Jonze ?','answer':'Max et les maximonstres','alternate':'','found':'false','lev':0.75},
            {'category':'SPL','question':'Quel célèbre jeu de logique tire son nom de l\'expression japonaise « nombre unique » ?','answer':'Sudoku','alternate':'','found':'false','lev':0.75},
            {'category':'GEO','question':'Dans quel pays la Meuse prend-elle sa source ?','answer':'France','alternate':'','found':'false','lev':0.75},
            {'category':'DIV','question':'Quel est le prénom de la grande couturière Coco Chanel ?','answer':'Gabrielle','alternate':'','found':'false','lev':0.75},
        ]},                
        {'name':'Wheatus','alternate':'','fullname':'Wheatus - Teenage Dirtbag','youtube':'https://www.youtube.com/watch?v=FC3y9llDXuM','quiz':[
            {'category':'HIS','question':'Quel pays a cédé la Floride aux États-Unis en 1819 par le Traité d\'Adams-Onis ?','answer':'L\'Espagne','alternate':'Espagne','found':'false','lev':0.75},
            {'category':'SCI','question':'Quelle profession est cataloguée comme étant la plus dangereuse au monde ?','answer':'La Pêche','alternate':'Pêche','found':'false','lev':0.75},
            {'category':'ART','question':'Quel musée a installé une antenne à Metz ?','answer':'Le Centre Pompidou','alternate':'Centre Pompidou','found':'false','lev':0.75},
            {'category':'SPL','question':'Quel célèbre jeu vidéo a été lancé par SEGA en 1991 pour promouvoir l\'incroyable vitesse de la Megadrive ?','answer':'Sonic','alternate':'','found':'false','lev':0.75},
        ]},                
        {'name':'Juanes','alternate':'','fullname':'Juanes - La Camisa Negra','youtube':'https://www.youtube.com/watch?v=7fwUH0oRmkQ','quiz':[
            {'category':'GEO','question':'Dans quel pays se trouve la région viticole du Piémont ?','answer':'Italie','alternate':'','found':'false','lev':0.75},
            {'category':'DIV','question':'Quel est le titre, hommage aux photographies de classe, du premier album de Stromae ?','answer':'Cheese','alternate':'','found':'false','lev':0.75},
            {'category':'HIS','question':'Quel nombre le chiffre romain « C » représente-t-il ?','answer':'100','alternate':'','found':'false','lev':1},
            {'category':'SCI','question':'Quelle saveur les chats ne peuvent-ils pas détecter ?','answer':'Sucré','alternate':'Le Sucre','found':'false','lev':0.75},
        ]},                
        {'name':'Michel Delpech','alternate':'','fullname':'Michel Delpech - Wight is Wight','youtube':'https://www.youtube.com/watch?v=a0ZunClGdXc','quiz':[
            {'category':'ART','question':'Quel nom donne-t-on au type de chapeau que portait Maurice Chevalier ?','answer':'Un Canotier','alternate':'canotier','found':'false','lev':0.75},
            {'category':'SPL','question':'Quel jeu a pu voir gagner des couples comme Les Meilleurs amis, Les Cousines marseillaises ou Les Inconnus ?','answer':'Pékin Express','alternate':'','found':'false','lev':0.75},
            {'category':'GEO','question':'Pour contenir quels animaux les Australiens ont-ils bâti la plus longue barrière au monde sur plus de 5 000 km ?','answer':'Les Dingos','alternate':'Dingos','found':'false','lev':0.75},
            {'category':'DIV','question':'Quel groupe a sorti l\'album Blonde comme moi ?','answer':'Les BB Brunes','alternate':'BB Brunes','found':'false','lev':0.75},
        ]},                
        {'name':'Les Poppys','alternate':'Poppys','fullname':'Poppys - Love Lioubov Amour','youtube':'https://www.youtube.com/watch?v=Njg2oA6-JuI','quiz':[
            {'category':'HIS','question':'Quel organisme français est né de la fusion de l\'ANPE et des Assedic ?','answer':'Pôle Emploi','alternate':'','found':'false','lev':0.75},
            {'category':'SCI','question':'Quels canaux transportent l\'œuf fertilisé jusqu\'à l\'utérus ?','answer':'Les Trompes de Fallope','alternate':'Trompes de Fallope','found':'false','lev':0.75},
            {'category':'ART','question':'Quel peintre français est connu pour ses tableaux et sculptures de danseuses ?','answer':'Edgard Degas','alternate':'Degas','found':'false','lev':0.75},
            {'category':'SPL','question':'Quel est le nombre maximum que l\'on peut atteindre sur un terrain de shuffleboard ?','answer':'10','alternate':'','found':'false','lev':1},
        ]},                
    ]},
];