// eslint-disable-next-line no-unused-vars
var songlist = 
[
{
    'listname':'exemple',
    'done':false,
    'theme':'Exemple',
    'nbwin':'1',
    'type':'single',
    'title':'Exemple',
    'subtitle':'On fait un test pour du beurre (Avec des anagrammes !)',
    'songs': [
        {'name':'Celine Dion','alternate':'','fullname':'Celine Dion','singletext':'Nicole Dine'},
        {'name':'Edith Piaf','alternate':'','fullname':'Edith Piaf','singletext':'Pied Hatif'},
        {'name':'Hélène Segara','alternate':'','fullname':'Cat Stevens','singletext':'Hélas Enragée'},
        {'name':'Vanessa Paradis','alternate':'','fullname':'Vanessa Paradis','singletext':'Panda Révassais'},
        {'name':'Chantal Goya','alternate':'','fullname':'Chantal Goya','singletext':'Yacht Angola'},
        {'name':'Marie Laforêt','alternate':'','fullname':'Marie Laforêt','singletext':'Lama Torrefié'},
    ]
},
{
    'listname':'mosaicexemple',
    'type':'mosaic',
    'done':false,
    'title':'Mosaïque - Exemple',
    'subtitle':'On recherche des Michels !',
    'songs': 
    [
        {'name':'Michel Blanc','alternate':'','fullname':'Michel Blanc','found':'false','index':'0','cover':0},
        {'name':'Michel Fugain','alternate':'','fullname':'Michel Fugain','found':'false','index':'1','cover':0},
        {'name':'Michèle Bernier','alternate':'','fullname':'Michèle Bernier','found':'false','index':'2','cover':0},
        {'name':'Michel Platini','alternate':'','fullname':'Michel Platini','found':'false','index':'3','cover':0},
        {'name':'Michel Cymes','alternate':'','fullname':'Michel Cymes','found':'false','index':'4','cover':0},
        {'name':'Michel Courtemanche','alternate':'','fullname':'Michel Courtemanche','found':'false','index':'5','cover':0},
        {'name':'Michel Berger','alternate':'','fullname':'Michel Berger','found':'false','index':'6','cover':0},
        {'name':'Michèle Alliot-Marie','alternate':'','fullname':'Michèle Alliot-Marie','found':'false','index':'7','cover':0},
        {'name':'Michel Serrault','alternate':'','fullname':'Michel Serrault','found':'false','index':'8','cover':0},
        {'name':'Michel Audiard','alternate':'','fullname':'Michel Audiard','found':'false','index':'9','cover':0},
        {'name':'Michel Delpech','alternate':'','fullname':'Michel Delpech','found':'false','index':'10','cover':0},
        {'name':'Michel Jonasz','alternate':'','fullname':'Michel Jonasz','found':'false','index':'11','cover':0},
        {'name':'Michel Drucker','alternate':'','fullname':'Michel Drucker','found':'false','index':'12','cover':0},
        {'name':'Michel Boujenah','alternate':'','fullname':'Michel Boujenah','found':'false','index':'13','cover':0},
        {'name':'Michèle Laroque','alternate':'','fullname':'Michèle Laroque','found':'false','index':'14','cover':0},
        {'name':'Michel Denisot','alternate':'','fullname':'Michel Denisot','found':'false','index':'15','cover':0},
        {'name':'Michel Polnareff','alternate':'','fullname':'Michel Polnareff','found':'false','index':'16','cover':0},
        {'name':'Coluche','alternate':'Michel Colucci','fullname':'Coluche','found':'false','index':'17','cover':0},
        {'name':'Michel Gondry','alternate':'','fullname':'Michel Gondry','found':'false','index':'18','cover':0},
        {'name':'Michel Vaillant','alternate':'','fullname':'Michel Vaillant','found':'false','index':'19','cover':0},
        {'name':'Michel Rocard','alternate':'','fullname':'Michel Rocard','found':'false','index':'20','cover':0},
        {'name':'Mimi Mathy','alternate':'Michèle Mathy','fullname':'Mimi Mathy','found':'false','index':'21','cover':0},
        {'name':'Michel Sardou','alternate':'','fullname':'Michel Sardou','found':'false','index':'22','cover':0},
        {'name':'Michel Galabru','alternate':'','fullname':'Michel Galabru','found':'false','index':'23','cover':0},
        {'name':'Michel Hazanavicius','alternate':'','fullname':'Michel Hazanavicius','found':'false','index':'24','cover':0},
    ]
},
{
    'listname':'journee',
    'type':'single',
    'done':false,
    'title':'Journée Mondiale',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Midnight Oil','alternate':'','fullname':'Midnight Oil - Beds are Burning','youtube':'https://www.youtube.com/watch?v=ejorQVy3m8E'},
        {'name':'Peter Gabriel','alternate':'','fullname':'Peter Gabriel - Biko','youtube':'https://www.youtube.com/watch?v=luVpsM3YAgw'},
        {'name':'Ennio Morricone','alternate':'Joan Baez','fullname':'Ennio Morricone - Joan Baez - Here\'s to You','youtube':'https://www.youtube.com/watch?v=R4xWbRBLj2I'},
        {'name':'Bob Dylan','alternate':'','fullname':'Bob Dylan - The Death of Emmett Till','youtube':'https://www.youtube.com/watch?v=Y2-DIJFJayc'},
        {'name':'Nina Simone','alternate':'','fullname':'Nina Simone - Mississipi Goddam','youtube':'https://www.youtube.com/watch?v=4tHYGfRot5w'},
        {'name':'Michel Delpech','alternate':'','fullname':'Michel Delpech - Les Divorcés','youtube':'https://www.youtube.com/watch?v=ReZO297WIp4'},
        {'name':'Peter Paul & Mary','alternate':'Peter Paul and Mary','fullname':'Peter Paul & Mary - Have You Been to Jail for Justice? ','youtube':'https://www.youtube.com/watch?v=tuwsjKvOIoQ'},
        {'name':'Maxime Le Forestier','alternate':'','fullname':'Maxime Le Forestier - La Vie D\'Un Homme','youtube':'https://www.youtube.com/watch?v=jAnMNLFwzcI'},
        {'name':'Sanseverino','alternate':'','fullname':'San Severino - Votez Papillon','youtube':'https://www.youtube.com/watch?v=bRF4Dt0DY08'},
        {'name':'Graeme Allwright','alternate':'','fullname':'Graeme Allwright - Qui a tué Davy Moore ?','youtube':'https://www.youtube.com/watch?v=4E09Az-ryjY'},
    ]
},
{
    'listname':'pochettes',
    'type':'mosaic',
    'done':false,
    'title':'Pochettes',
    'subtitle':'On recherche le nom de l\'interprète de l\'album (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Marvin Gaye','alternate':'','fullname':'Marvin Gaye','found':'false','index':'0','cover':0},
        {'name':'Lou Reed','alternate':'','fullname':'Lou Reed','found':'false','index':'1','cover':0},
        {'name':'Jack White','alternate':'','fullname':'Jack White','found':'false','index':'2','cover':0},
        {'name':'Joan Baez','alternate':'','fullname':'Joan Baez','found':'false','index':'3','cover':0},
        {'name':'Leon Russell','alternate':'','fullname':'Leon Russell','found':'false','index':'4','cover':0},
        {'name':'Deep Purple','alternate':'','fullname':'Deep Purple','found':'false','index':'5','cover':0},
        {'name':'Supertramp','alternate':'','fullname':'Supertramp','found':'false','index':'6','cover':0},
        {'name':'T.Rex','alternate':'','fullname':'T.Rex','found':'false','index':'7','cover':0},
        {'name':'Alan Parsons Project','alternate':'Alan Parson','fullname':'Alan Parsons Project','found':'false','index':'8','cover':0},
        {'name':'King Crimson','alternate':'','fullname':'King Crimson','found':'false','index':'9','cover':0},
        {'name':'Jethro Tull','alternate':'','fullname':'Jethro Tull','found':'false','index':'10','cover':0},
        {'name':'The Doors','alternate':'Doors','fullname':'The Doors','found':'false','index':'11','cover':0},
        {'name':'Cat Stevens','alternate':'','fullname':'Cat Stevens','found':'false','index':'12','cover':0},
        {'name':'Genesis','alternate':'','fullname':'Genesis','found':'false','index':'13','cover':0},
        {'name':'Elton John','alternate':'','fullname':'Elton John','found':'false','index':'14','cover':0},
        {'name':'Fleetwood Mac','alternate':'','fullname':'Fleetwood Mac','found':'false','index':'15','cover':0},
        {'name':'Sugarhill Gang','alternate':'','fullname':'Sugarhill Gang','found':'false','index':'16','cover':0},
        {'name':'Simon & Garfunkel','alternate':'Simon and Garfunkel','fullname':'Simon & Garfunkel','found':'false','index':'17','cover':0},
        {'name':'Heart','alternate':'','fullname':'Heart','found':'false','index':'18','cover':0},
        {'name':'Maxime Le Forestier','alternate':'Maxime LeForestier','fullname':'Maxime Le Forestier','found':'false','index':'19','cover':0},
        {'name':'Jean Michel Jarre','alternate':'','fullname':'Jean Michel Jarre','found':'false','index':'20','cover':0},
        {'name':'The Grateful Dead','alternate':'Grateful Dead','fullname':'The Grateful Dead','found':'false','index':'21','cover':0},
        {'name':'Peter Frampton','alternate':'','fullname':'Peter Frampton','found':'false','index':'22','cover':0},
        {'name':'Magma','alternate':'','fullname':'Magma','found':'false','index':'23','cover':0},
        {'name':'Graeme Allwright','alternate':'','fullname':'Graeme Allwright','found':'false','index':'24','cover':0},
        {'name':'Pink Floyd','alternate':'','fullname':'Pink Floyd','found':'false','index':'25','cover':0},
        {'name':'The Beatles','alternate':'Beatles','fullname':'The Beatles','found':'false','index':'26','cover':0},
        {'name':'Leonard Cohen','alternate':'','fullname':'Leonard Cohen','found':'false','index':'27','cover':0},
        {'name':'Brigitte','alternate':'','fullname':'Brigitte','found':'false','index':'28','cover':0},
        {'name':'Michael Jackson','alternate':'','fullname':'Michael Jackson','found':'false','index':'29','cover':0},
        {'name':'Angèle','alternate':'','fullname':'Angèle','found':'false','index':'30','cover':0},
        {'name':'Bob Dylan','alternate':'','fullname':'Bob Dylan','found':'false','index':'31','cover':0},
        {'name':'Redbone','alternate':'','fullname':'Redbone','found':'false','index':'32','cover':0},
        {'name':'Jimi Hendrix','alternate':'','fullname':'Jimi Hendrix','found':'false','index':'33','cover':0},
        {'name':'Boston','alternate':'','fullname':'Boston','found':'false','index':'34','cover':0},
        {'name':'Billy Joel','alternate':'','fullname':'Billy Joel','found':'false','index':'35','cover':0},
        {'name':'Kiss','alternate':'','fullname':'Kiss','found':'false','index':'36','cover':0},
        {'name':'Led Zeppelin','alternate':'','fullname':'Led Zeppelin','found':'false','index':'37','cover':0},
        {'name':'Cream','alternate':'','fullname':'Cream','found':'false','index':'38','cover':0},
        {'name':'Joe Cocker','alternate':'','fullname':'Joe Cocker','found':'false','index':'39','cover':0},
        {'name':'Mike Oldfield','alternate':'','fullname':'Mike Oldfield','found':'false','index':'40','cover':0},
        {'name':'Renaud','alternate':'','fullname':'Renaud','found':'false','index':'41','cover':0},
        {'name':'The Who','alternate':'Who','fullname':'The Who','found':'false','index':'42','cover':0},
        {'name':'Eagles','alternate':'The Eagles','fullname':'Eagles','found':'false','index':'43','cover':0},
    ]
},
{
    'listname':'aledjoub7',
    'done':false,
    'type':'single',
    'title':'Aledjoub #7',
    'subtitle':'Chansons à l\'envers ! On recherche le nom de l\'interprète (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Veronique Sanson','alternate':'','fullname':'Veronique Sanson - Rien que de l\'eau','youtube':'https://www.youtube.com/watch?v=0t0H-j6qEzo'},
        {'name':'Les Rita Mitsouko','alternate':'Rita Mitsouko','fullname':'Les Rita Mitsouko - C\'est Comme ça','youtube':'https://www.youtube.com/watch?v=fGZRVGlGZ6A'},
        {'name':'Boney M','alternate':'','fullname':'Boney M - Rasputin','youtube':'https://www.youtube.com/watch?v=AbSXWsWDbm4'},
        {'name':'a-ha','alternate':'aha','fullname':'a-ha - Take On Me','youtube':'https://www.youtube.com/watch?v=djV11Xbc914'},
        {'name':'Luis Fonsi','alternate':'','fullname':'Luis Fonsi - Despacito','youtube':'https://www.youtube.com/watch?v=kJQP7kiw5Fk'},
        {'name':'Daniel Balavoine','alternate':'','fullname':'Daniel Balavoine - Je ne suis pas un héros','youtube':'https://www.youtube.com/watch?v=tYnPAxnrzxY'},
        {'name':'M.I.A.','alternate':'MIA','fullname':'M.I.A. - Paper Planes','youtube':'https://www.youtube.com/watch?v=ewRjZoRtu0Y'},
        {'name':'PSY','alternate':'','fullname':'PSY - Gangnam Style','youtube':'https://www.youtube.com/watch?v=9bZkp7q19f0'},
        {'name':'Kyo','alternate':'','fullname':'Kyo - Dernière Danse','youtube':'https://www.youtube.com/watch?v=aU_TQcyGkvY'},
        {'name':'Renan Luce','alternate':'','fullname':'Renan Luce - La Lettre','youtube':'https://www.youtube.com/watch?v=UR1GZrzizXM'},
        {'name':'Zazie','alternate':'','fullname':'Zazie - Un Point C\'est Tout','youtube':'https://www.youtube.com/watch?v=yMEj1qgHADc'},
        {'name':'Status Quo','alternate':'','fullname':'Status Quo - In The Army Now','youtube':'https://www.youtube.com/watch?v=EIxsPBbZ_b8'},
    ]
},
{
    'listname':'enfance',
    'done':false,
    'type':'single',
    'title':'L\'idole des jeunes',
    'subtitle':'On recherche le nom d\'un interprète (Prénom + Nom) dont voici une photo d\'enfance !',
    'songs': [
        {'name':'Jim Morrison','alternate':'','fullname':'Jim Morrison'},
        {'name':'Johnny Hallyday','alternate':'','fullname':'Johnny Hallyday'},
        {'name':'Katy Perry','alternate':'','fullname':'Katy Perry'},
        {'name':'Elton John','alternate':'','fullname':'Elton John'},
        {'name':'Amel Bent','alternate':'','fullname':'Amel Bent'},
        {'name':'Madonna','alternate':'','fullname':'Madonna'},
        {'name':'Stromae','alternate':'','fullname':'Stromae'},
        {'name':'Bjork','alternate':'','fullname':'Bjork'},
        {'name':'Elvis Presley','alternate':'','fullname':'Elvis Presley'},
        {'name':'Patrick Bruel','alternate':'','fullname':'Patrick Bruel'},
        {'name':'Lady Gaga','alternate':'','fullname':'Lady Gaga'},
        {'name':'Amy Winehouse','alternate':'','fullname':'Amy Winehouse'},
        {'name':'Rihanna','alternate':'','fullname':'Rihanna'},
        {'name':'Eminem','alternate':'','fullname':'Eminem'},
        {'name':'Paul McCartney','alternate':'','fullname':'Paul McCartney'},
        {'name':'Beyonce','alternate':'','fullname':'Beyonce'},
        {'name':'Michel Polnareff','alternate':'','fullname':'Michel Polnareff'},
        {'name':'Jack Black','alternate':'','fullname':'Jack Black'},
    ]
},
{
    'listname':'politique',
    'done':false,
    'type':'single',
    'title':'Tout est politique',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Mecano','alternate':'','fullname':'Mecano - Une Femme avec une Femme','youtube':'https://www.youtube.com/watch?v=JtBSjvNPKGs'},
        {'name':'Boris Vian','alternate':'','fullname':'Boris Vian - Le Déserteur','youtube':'https://www.youtube.com/watch?v=yWm3HORSFzU'},
        {'name':'P!nk','alternate':'Pink','fullname':'P!nk - So What','youtube':'https://www.youtube.com/watch?v=FJfFZqTlWrQ'},
        {'name':'First Aid Kit','alternate':'','fullname':'First Aid Kit - You Are The Problem Here','youtube':'https://www.youtube.com/watch?v=exsaCN4c5dc'},
        {'name':'Aretha Franklin','alternate':'','fullname':'Aretha Franklin - Think','youtube':'https://www.youtube.com/watch?v=tc36-Li5eww'},
        {'name':'Pierre Perret','alternate':'','fullname':'Pierre Perret - Lily','youtube':'https://www.youtube.com/watch?v=urVfi9Yswaw'},
        {'name':'IAM','alternate':'','fullname':'IAM - Nés sous la même étoile','youtube':'https://www.youtube.com/watch?v=rn_UjJN3YQU'},
        {'name':'Trust','alternate':'','fullname':'Trust - Police Milice','youtube':'https://www.youtube.com/watch?v=hJfLEQvf9qY'},
        {'name':'Didier Super','alternate':'','fullname':'Didier Super - Manipulez Nous Mieux','youtube':'https://www.youtube.com/watch?v=Xgw9Y_j8VLk'},
        {'name':'Rage Against The Machine','alternate':'','fullname':'Rage Against The Machine - Killing in the Name Of','youtube':'https://www.youtube.com/watch?v=bWXazVhlyxQ'},
        {'name':'Billie Holiday','alternate':'','fullname':'Billie Holiday - Strange Fruit','youtube':'https://www.youtube.com/watch?v=Lx_mOECjT_8'},
        {'name':'Anne Sylvestre','alternate':'','fullname':'Anne Sylvestre - La faute à Eve','youtube':'https://www.youtube.com/watch?v=msw1sNs6ISw'},       
    ]
},
{
    'listname':'espagnol',
    'done':false,
    'type':'single',
    'title':'¿Pero alors eres francés ?',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Marie Myriam','alternate':'','fullname':'Marie Myriam - El Zagal Y El Ave Azul','youtube':'https://www.youtube.com/watch?v=b08axweDcyY'},
        {'name':'Georges Moustaki','alternate':'','fullname':'Georges Moustaki - El Extranjero','youtube':'https://www.youtube.com/watch?v=-SKLpm42jj0'},
        {'name':'ABBA','alternate':'','fullname':'ABBA - Fernando ','youtube':'https://www.youtube.com/watch?v=bprrWMQ9DDY'},
        {'name':'Patrick Bruel','alternate':'','fullname':'Patrick Bruel - En la plaza de los Heroes','youtube':'https://www.youtube.com/watch?v=kAwrOECANYI'},
        {'name':'Laurent Voulzy','alternate':'','fullname':'Laurent Voulzy - Corazon Granadin','youtube':'https://www.youtube.com/watch?v=xlrp2MhaN4A'},
        {'name':'Beyonce','alternate':'','fullname':'Beyonce - Si Yo Fuera Un Chico','youtube':'https://www.youtube.com/watch?v=EUB4YMBLvXk'},
        {'name':'Axelle Red','alternate':'','fullname':'Axelle Red - Sensualidad','youtube':'https://www.youtube.com/watch?v=68U1SaBgJL8'},
        {'name':'Celine Dion','alternate':'','fullname':'Celine Dion - All By Myself','youtube':'https://www.youtube.com/watch?v=4KMPs5fspKE'},
        {'name':'Francis Cabrel','alternate':'','fullname':'Francis Cabrel - La quiero a morir','youtube':'https://www.youtube.com/watch?v=JBv-TUZlkTc'},
        {'name':'Michel Delpech','alternate':'','fullname':'Michel Delpech - Con Marian Yo Conoci Paris','youtube':''},
        {'name':'Michel Fugain','alternate':'','fullname':'Michel Fugain - Una Bella Historia','youtube':'https://www.youtube.com/watch?v=zHlhN6SVyk8'},
        {'name':'Georges Brassens','alternate':'','fullname':'Georges Brassens - La Pata de Juana','youtube':'https://www.youtube.com/watch?v=4uCuWVRsv10'},
    ]
},
{
    'listname':'voisins',
    'done':false,
    'type':'single',
    'title':'Fête des Voisins',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Téléphone','alternate':'Telephone','fullname':'Téléphone - New York Avec Toi','youtube':'https://www.youtube.com/watch?v=aWROzt7kudk'},
        {'name':'Mylène Farmer','alternate':'','fullname':'Mylène Farmer - Sans Contrefaçon','youtube':'https://www.youtube.com/watch?v=81n6g267Pyo'},
        {'name':'The Buggles','alternate':'Buggles','fullname':'The Buggles - Video Killed The Radio Star','youtube':'https://www.youtube.com/watch?v=LrjdpNDfZLo'},
        {'name':'Stromae','alternate':'','fullname':'Stromae - Alors on danse','youtube':'https://youtu.be/VHoT4N43jK8'},
        {'name':'Blondie','alternate':'','fullname':'Blondie - Heart of Glass','youtube':'https://www.youtube.com/watch?v=WGU_4-5RaxU'},
        {'name':'Supertramp','alternate':'','fullname':'Supertramp - Breakfast in America','youtube':'https://www.youtube.com/watch?v=PZahtmWhH5g'},
        {'name':'Yes','alternate':'','fullname':'Yes - Owner of a Lonely Heart','youtube':'https://www.youtube.com/watch?v=IG_VDj8Eh_g'},
        {'name':'AC/DC','alternate':'ACDC','fullname':'AC/DC - Highway to Hell','youtube':'https://www.youtube.com/watch?v=l482T0yNkeo'},
        {'name':'Zebda','alternate':'','fullname':'Zebda - Tomber la Chemise','youtube':'https://www.youtube.com/watch?v=4y4D-evzDTo'},
        {'name':'Daft Punk','alternate':'','fullname':'Daft Punk - One More Time','youtube':'https://www.youtube.com/watch?v=wU26xVT_vBU'},
        {'name':'Soft Cell','alternate':'','fullname':'Soft Cell - Tainted Love','youtube':'https://www.youtube.com/watch?v=XZVpR3Pk-r8'},
        {'name':'Pink Floyd','alternate':'','fullname':'Pink Floyd - Another Brick In The Wall pt II','youtube':'https://youtu.be/HrxX9TBj2zY'},
    ]
},
{
    'listname':'rockabye',
    'done':false,
    'type':'single',
    'title':'Une chanson douce... ',
    'subtitle':'On recherche le nom de l\'interprète original (Prénom + Nom / Groupe) !',
    'songs': [
        {'name':'Eagles','alternate':'The Eagles','fullname':'Eagles - Hotel California','youtube':'https://www.youtube.com/watch?v=x0OzUQi8uAo'},
        {'name':'Queen','alternate':'','fullname':'Queen - Bohemian Rhapsody','youtube':'https://www.youtube.com/watch?v=rx46tEekNKc'},
        {'name':'Black Sabbath','alternate':'','fullname':'Black Sabbath - War Pigs','youtube':'https://www.youtube.com/watch?v=sGdmAggX5i4'},
        {'name':'The Grateful Dead','alternate':'Grateful Dead','fullname':'The Grateful Dead - Ripple','youtube':'https://www.youtube.com/watch?v=9NVaYcMt0ns'},
        {'name':'Taylor Swift','alternate':'','fullname':'Taylor Swift - Shake It Off','youtube':'https://www.youtube.com/watch?v=892Glljtlqs'},
        {'name':'Guns N Roses','alternate':'Guns N\' Roses','fullname':'Guns N Roses - Sweet Child O\' Mine','youtube':'https://www.youtube.com/watch?v=KJAay6Pc47M'},
        {'name':'Katy Perry','alternate':'','fullname':'Katy Perry - Roar','youtube':'https://www.youtube.com/watch?v=BqZeTj6qCUk'},
        {'name':'Kiss','alternate':'','fullname':'Kiss - I Was Made For Loving You','youtube':'https://www.youtube.com/watch?v=H8Jtrx1w1XA'},
        {'name':'Fleetwood Mac','alternate':'','fullname':'Fleetwood Mac - Go Your Own Way','youtube':'https://www.youtube.com/watch?v=Js7bKbsCUSg'},
        {'name':'Weezer','alternate':'','fullname':'Weezer - Island in the Sun','youtube':'https://www.youtube.com/watch?v=aSXDIMPX2hE'},
        {'name':'Johnny Cash','alternate':'','fullname':'Johnny Cash - Ring of Fire','youtube':'https://www.youtube.com/watch?v=QO5H_DTKTkA'},
        {'name':'Led Zeppelin','alternate':'','fullname':'Led Zeppelin - Dazed and Confused','youtube':'https://www.youtube.com/watch?v=VirDpHMb_qA'},
    ]
},
];